### PR TITLE
Update ui-router-react and ui-router-visualizer

### PR DESCRIPTION
**Pull request by xtforgame**
Updated ```ui-router-react``` and ```ui-router-visualizer``` packages and add ```cross-env``` package for Windows users

Modified some code to fit to the new api of ui-router-react 0.4.0

### CODE REVIEW

**Comment by elboman** [comment]
Great! Thanks for the PR, I was going to update the sample soon but I'm kinda full of work lately. It seems fine, I'll take a deeper look and merge asap!

The sample application is built inside the `/docs` folder in order for github to pick it and deploy it on github pages. It would be helpful if you grant me access for editing the PR so I can build the app when merging your PR ;)

**Comment by xtforgame** [comment]
Hi @elboman,
I don't know how to grant you access for this PR, so I add you to the Collaborators of my repo. , I'm not sure is it helpful.

I also find a minor issue after updating: 
Always get the following error at the first time I enter this app:
```
TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'welcome'{} ))
```

I am appreciated if someone could help to solve that :)

**Comment by elboman** [comment]
There should be a `Allow edits from maintainers` option in the sidebar, but the access to your branch is also fine.

I'll have a look at the error later and let you know.

**Comment by uditalias** [comment]
+1 for the @xtforgame first time TransitionRejection problem

**Comment by christopherthielen** [comment]
Whoops, I didn't notice this PR already existed.  I made another one which looks almost exactly the same #2

**Comment by elboman** [comment]
I close this one as #2 updates to a more recent version, thanks!

**Pull request closed without merging**
